version: "3.9"

services:
    nginx:
        build:
            context: nginx
        ports:
            - "80:80"
        restart: always
        container_name: inc_nginx
        volumes:
            - "../.data/wordpress:/var/www"
            - "../.data/adminer:/var/adminer"
    wordpress:
        build:
            context: wordpress
        restart: always
        container_name: inc_wp
        volumes:
            - "../.data/wordpress:/var/www"
    mysql:
        build:
            context: mysql
        restart: always
        container_name: inc_mysql
        volumes:
            - "../.data/mysql:/var/lib/mysql"
    adminer:
        build:
            context: adminer
        restart: always
        container_name: inc_adm
        volumes:
            - "../.data/adminer:/var/adminer"
