version: "3.9"

services:
    nginx:
        build:
            context: nginx
        ports:
            - "80:80"
        restart: always
        container_name: inc_nginx
        volumes:
            - "../.data/wordpress:/var/www"
            #- "../.data/phpmyadmin:/var/www/pma"
    wordpress:
        build:
            context: wordpress
        restart: always
        container_name: inc_wp
        volumes:
            - "../.data/wordpress:/var/www"
    mysql:
        build:
            context: mysql
        restart: always
        container_name: inc_mysql
        volumes:
            - "../.data/mysql:/var/lib/mysql"
    #pma:
        #build:
            #context: phpmyadmin
        #restart: always
        #container_name: inc_pma
        #volumes:
            #- "../.data/phpmyadmin:/var/www/pma"
